import { Category, CreatorVideo, Prompt, User } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-cinematic', name: 'Cinematic', slug: 'cinematic', description: 'Hollywood-grade widescreen composition, anamorphic lenses, and movie lighting', order: 1, isEnabled: true },
  { id: 'cat-product', name: 'Product Videos', slug: 'product-videos', description: 'Luxury advertising, macro textures, rotating podiums, studio lighting', order: 2, isEnabled: true },
  { id: 'cat-character', name: 'Character Animation', slug: 'character-animation', description: 'Expressive avatars, stylized protagonists, and fluid choreography', order: 3, isEnabled: true },
  { id: 'cat-storytelling', name: 'Storytelling', slug: 'storytelling', description: 'Dramatic narrative sequences, emotional character arcs, and multi-shot pacing', order: 4, isEnabled: true },
  { id: 'cat-ads', name: 'Ads & Marketing', slug: 'ads-marketing', description: 'High-conversion commercials, vibrant typography space, and snappy hooks', order: 5, isEnabled: true },
  { id: 'cat-social', name: 'Social Media', slug: 'social-media', description: 'Viral aesthetic styles, trending kinetic transitions, and high-energy cuts', order: 6, isEnabled: true },
  { id: 'cat-youtube', name: 'YouTube', slug: 'youtube', description: 'B-roll sequences, intro hooks, explainer backdrops, and cinematic cutaways', order: 7, isEnabled: true },
  { id: 'cat-shorts', name: 'Shorts/Reels', slug: 'shorts-reels', description: '9:16 vertical video compositions, fast pacing, and instant visual stops', order: 8, isEnabled: true },
  { id: 'cat-realistic', name: 'Realistic Videos', slug: 'realistic-videos', description: 'Hyper-detailed documentary realism, physics-accurate motion, and lifelike skin', order: 9, isEnabled: true },
  { id: 'cat-fantasy', name: 'Fantasy', slug: 'fantasy', description: 'Ethereal spellcraft, mystical kingdoms, floating islands, and magical bioluminescence', order: 10, isEnabled: true },
  { id: 'cat-scifi', name: 'Sci-Fi', slug: 'sci-fi', description: 'Cyberpunk dystopias, neon megastructures, warp drives, and futuristic robotics', order: 11, isEnabled: true },
  { id: 'cat-horror', name: 'Horror', slug: 'horror', description: 'Psychological tension, low-key lighting, shadowy silhouettes, and uncanny suspense', order: 12, isEnabled: true },
  { id: 'cat-nature', name: 'Nature', slug: 'nature', description: 'Epic sweeping landscapes, time-lapses, weather systems, and aerial drone tracking', order: 13, isEnabled: true },
  { id: 'cat-animals', name: 'Animals', slug: 'animals', description: 'Wildlife macro photography, dynamic predatory sprints, and natural habitats', order: 14, isEnabled: true },
  { id: 'cat-travel', name: 'Travel', slug: 'travel', description: 'Golden hour drone sweeps, bustling markets, scenic coastlines, and cultural voyages', order: 15, isEnabled: true },
  { id: 'cat-food', name: 'Food', slug: 'food', description: 'Mouthwatering slow-motion sizzles, steam curls, caramel drizzles, and culinary elegance', order: 16, isEnabled: true },
  { id: 'cat-fashion', name: 'Fashion', slug: 'fashion', description: 'Haute couture runway strides, dramatic fabric billow, wind machines, and vogue framing', order: 17, isEnabled: true },
  { id: 'cat-education', name: 'Education', slug: 'education', description: 'Scientific visualizations, microscopic biological flythroughs, and planetary orbits', order: 18, isEnabled: true },
  { id: 'cat-3d', name: '3D Animation', slug: '3d-animation', description: 'Pixar/Dreamworks stylized renders, subsurface scattering, and bouncy character physics', order: 19, isEnabled: true },
  { id: 'cat-vfx', name: 'VFX', slug: 'vfx', description: 'Particle explosions, liquid metal morphs, shockwaves, and hyper-stylized energy blasts', order: 20, isEnabled: true },
  { id: 'cat-experimental', name: 'Experimental', slug: 'experimental', description: 'Surrealist dreamscapes, abstract motion geometry, and non-Euclidean camera trickery', order: 21, isEnabled: true },
  { id: 'cat-other', name: 'Other', slug: 'other', description: 'Unique creator concepts and custom generative experiments', order: 22, isEnabled: true }
];

export const INITIAL_PROMPTS: Prompt[] = [
  {
    id: 'prompt-1',
    title: 'Cyberpunk Neon Rain Alley Tracking Shot',
    description: 'A relentless low-angle tracking shot following a trench-coated detective navigating a glistening cyberpunk alley drenched in holographic neon reflections.',
    category: 'Sci-Fi',
    tags: ['Cyberpunk', 'Cinematic', 'Neon', 'Rain', 'Runway Gen-3', 'Tracking Shot'],
    thumbnail: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    fullPrompt: 'Cinematic 35mm anamorphic footage of [SUBJECT] walking purposefully through [LOCATION]. Puddles on asphalt reflect violet and amber neon billboards. Heavy volumetric rain cascades under flickering streetlights. [CAMERA MOVEMENT], maintaining razor-sharp focus on the drenched fabric with soft anamorphic oval bokeh in the backdrop. [LIGHTING], 2.39:1 aspect ratio, 24fps motion cadence, Kodachrome color grade, [MOOD].',
    exampleOutput: 'Generates an atmospheric neo-noir sequence with hyper-realistic water droplet physics, steam rising from grates, and fluid camera tracking.',
    recommendedUse: 'Runway Gen-3 Alpha, Kling 1.5 Pro, Sora',
    creationDate: '2026-03-01',
    updatedDate: '2026-03-04',
    featuredStatus: true,
    accessLevel: 'FREE',
    customizableVariables: [
      { key: 'SUBJECT', label: 'Subject', defaultValue: 'a solitary cybernetic investigator with illuminated ocular implants' },
      { key: 'LOCATION', label: 'Location', defaultValue: 'a crowded Neo-Shinjuku back-alley overflowing with noodle stalls and cable tangles' },
      { key: 'CAMERA MOVEMENT', label: 'Camera Movement', defaultValue: 'Smooth low-angle Steadicam backward tracking shot at knee level' },
      { key: 'LIGHTING', label: 'Lighting', defaultValue: 'High-contrast rim lighting from cyan store signs contrasted against deep moody shadows' },
      { key: 'MOOD', label: 'Mood', defaultValue: 'melancholic, gritty, tense, and atmospheric' }
    ],
    copiesCount: 2840,
    savesCount: 1420,
    isPublished: true,
    authorName: 'PromptVault Studio'
  },
  {
    id: 'prompt-2',
    title: 'Luxury Perfume Bottle Splash & Gold Dust',
    description: 'Ultra slow-motion commercial product reveal with crystal-clear liquid ribbons and suspended 24k gold leaf particles.',
    category: 'Product Videos',
    tags: ['Product', 'Luxury', 'Slow Motion', 'Commercial', 'Macro', '4K'],
    thumbnail: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
    fullPrompt: 'Hyper-detailed 1000fps Phantom Flex commercial video of [SUBJECT] resting on [LOCATION]. A viscous ribbon of crystalline amber liquid cascades in slow-motion around the curved silhouette. Microscopic suspended gold flecks catch directional highlights. [CAMERA MOVEMENT], macro lens f/2.8 with shallow depth of field. [LIGHTING], pristine commercial studio color grading, [MOOD].',
    exampleOutput: 'Produces a pristine high-end luxury advertisement sequence with photorealistic caustics and fluid droplet refraction.',
    recommendedUse: 'Luma Dream Machine, Kling 1.5, Runway Gen-3',
    creationDate: '2026-02-28',
    updatedDate: '2026-03-02',
    featuredStatus: true,
    accessLevel: 'FREE',
    customizableVariables: [
      { key: 'SUBJECT', label: 'Subject', defaultValue: 'an obsidian and beveled glass luxury cologne bottle with engraved gold typography' },
      { key: 'LOCATION', label: 'Location', defaultValue: 'a matte black slate turntable surrounded by gentle water ripples' },
      { key: 'CAMERA MOVEMENT', label: 'Camera Movement', defaultValue: 'Slow rotational 360-degree orbital pan rising slightly from 45 degrees' },
      { key: 'LIGHTING', label: 'Lighting', defaultValue: 'Dual softbox key lighting with a crisp golden edge rim light' },
      { key: 'MOOD', label: 'Mood', defaultValue: 'prestigious, sensual, immaculate, and ultra-refined' }
    ],
    copiesCount: 1980,
    savesCount: 970,
    isPublished: true,
    authorName: 'Aura Media'
  },
  {
    id: 'prompt-3',
    title: 'Epic Mountain Ridge Golden Hour Drone Flyover',
    description: 'Breathtaking 8K cinematic FPV drone sweeping over jagged alpine peaks bathed in warm alpenglow and morning mist.',
    category: 'Nature',
    tags: ['Drone', 'Nature', 'Landscape', 'Golden Hour', 'Cinematic', '8K'],
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
    fullPrompt: 'Breathtaking IMAX 70mm aerial drone sequence sweeping at high velocity across [LOCATION]. In the foreground, [SUBJECT] stands gazing toward the horizon. Wispy valley fog drifts between pine forests below. [CAMERA MOVEMENT], ultra wide angle 14mm lens with zero barrel distortion. [LIGHTING], natural atmospheric haze, cinematic contrast, [MOOD].',
    exampleOutput: 'Creates a heart-pounding sweeping mountain sequence with realistic depth perception, wind movement on clothing, and golden light wash.',
    recommendedUse: 'Runway Gen-3 Alpha, Hailuo Minimax, Kling 1.5',
    creationDate: '2026-03-02',
    updatedDate: '2026-03-05',
    featuredStatus: false,
    accessLevel: 'PLUS',
    customizableVariables: [
      { key: 'SUBJECT', label: 'Subject', defaultValue: 'a lone mountaineer in crimson technical gear holding trekking poles' },
      { key: 'LOCATION', label: 'Location', defaultValue: 'a razor-sharp snow-dusted dolomite ridge towering 3,000 meters above sea level' },
      { key: 'CAMERA MOVEMENT', label: 'Camera Movement', defaultValue: 'Rapid FPV dive over the cliff ledge, pulling up into a wide majestic altitude reveal' },
      { key: 'LIGHTING', label: 'Lighting', defaultValue: 'Blazing golden hour sunset with warm orange alpenglow kissing snowy crests' },
      { key: 'MOOD', label: 'Mood', defaultValue: 'awe-inspiring, solitary, adventurous, and transcendent' }
    ],
    copiesCount: 1540,
    savesCount: 820,
    isPublished: true,
    authorName: 'EarthVision'
  },
  {
    id: 'prompt-4',
    title: 'Haute Couture Avant-Garde Runway Strut',
    description: 'High-fashion editorial runway clip with undulating metallic fabrics, strobe lights, and fierce supermodel pacing.',
    category: 'Fashion',
    tags: ['Fashion', 'Runway', 'Vogue', 'Editorial', 'Slow Mo'],
    thumbnail: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
    fullPrompt: 'High fashion editorial runway video shot on Arri Alexa Mini LF. [SUBJECT] strides dynamically down [LOCATION]. The structural garment ripples and shimmers with liquid metallic iridescence with every step. [CAMERA MOVEMENT], tracking smoothly at waist height. [LIGHTING], editorial high fashion color tone, 60fps slowed to 24fps cinema playback, [MOOD].',
    exampleOutput: 'Renders natural fabric dynamics, fabric drag, floor reflections, and professional runway choreography.',
    recommendedUse: 'Kling 1.5 Pro, Runway Gen-3 Alpha',
    creationDate: '2026-03-03',
    updatedDate: '2026-03-04',
    featuredStatus: false,
    accessLevel: 'PLUS',
    customizableVariables: [
      { key: 'SUBJECT', label: 'Subject', defaultValue: 'an ethereal runway model wearing an architectural chrome and pleated silk origami gown' },
      { key: 'LOCATION', label: 'Location', defaultValue: 'a mirrored runway flanked by minimalist brutalist concrete arches' },
      { key: 'CAMERA MOVEMENT', label: 'Camera Movement', defaultValue: 'Smooth frontal tracking dolly retreating slightly faster than the model stride' },
      { key: 'LIGHTING', label: 'Lighting', defaultValue: 'High-intensity cool white top spotlights with stark shadow geometry on the glossy floor' },
      { key: 'MOOD', label: 'Mood', defaultValue: 'fierce, avant-garde, commanding, and mesmerizing' }
    ],
    copiesCount: 920,
    savesCount: 460,
    isPublished: true,
    authorName: 'VogueAI'
  },
  {
    id: 'prompt-5',
    title: 'Deep Space Hyperdrive Collapse & Starfleet Fleet',
    description: 'Mind-bending sci-fi warpspace sequence showing a colossal flagship exiting hyperspace into an active asteroid dogfight.',
    category: 'Sci-Fi',
    tags: ['Sci-Fi', 'Space', 'VFX', 'Spaceship', 'Hyperdrive', 'CGI'],
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    fullPrompt: 'Epic space opera cinematic visual effects shot. The cosmic vacuum of [LOCATION] suddenly distorts with gravitational gravitational lensing. Suddenly [SUBJECT] emerges from a blinding cyan hyperspace rupture, displacing space dust and micro-meteorites. [CAMERA MOVEMENT], 50mm anamorphic lens with chromatic aberration. [LIGHTING], zero-gravity physics, photorealistic hull greebles, [MOOD].',
    exampleOutput: 'Delivers jaw-dropping relativistic space bending, engine plasma trails, and intricate industrial spaceship surface detailing.',
    recommendedUse: 'Runway Gen-3 Alpha, Sora, Kling 1.5',
    creationDate: '2026-03-01',
    updatedDate: '2026-03-03',
    featuredStatus: true,
    accessLevel: 'PRO',
    customizableVariables: [
      { key: 'SUBJECT', label: 'Subject', defaultValue: 'a three-kilometer-long titanium dreadnought with glowing cerulean ionic thrusters' },
      { key: 'LOCATION', label: 'Location', defaultValue: 'a dense planetary ring system orbiting a violet gas giant with twin binary suns' },
      { key: 'CAMERA MOVEMENT', label: 'Camera Movement', defaultValue: 'Dramatic Dutch-angle crane shot swooping past the command bridge into the weapon batteries' },
      { key: 'LIGHTING', label: 'Lighting', defaultValue: 'Harsh celestial sunlight contrasting against pitch black void shadows and blue plasma flares' },
      { key: 'MOOD', label: 'Mood', defaultValue: 'monumental, cataclysmic, exhilarating, and hyper-futuristic' }
    ],
    copiesCount: 3120,
    savesCount: 1650,
    isPublished: true,
    authorName: 'Orbital Vfx'
  },
  {
    id: 'prompt-6',
    title: 'Artisan Burger Gourmet Melt & Flame Grill Macro',
    description: 'Sizzling culinary masterpiece video capturing aged cheddar melting over a seared wagyu patty with caramelized onion smoke.',
    category: 'Food',
    tags: ['Food', 'Culinary', 'Commercial', 'Macro', 'Sizzle', 'Delicious'],
    thumbnail: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    fullPrompt: 'Ultra-slow motion 4K food commercial sequence. Extreme macro close-up of [SUBJECT] cooking over [LOCATION]. Thick molten aged cheese bubbles and stretches downward across the charred crust while aromatic smoke curls into the warm air. [CAMERA MOVEMENT], 100mm macro probe lens. [LIGHTING], appetizing warm color calibration, shallow depth of field, [MOOD].',
    exampleOutput: 'Creates irresistible culinary b-roll with realistic sizzle bubbles, radiant heat waves, and gloss texture.',
    recommendedUse: 'Luma Dream Machine, Kling 1.5, Runway Gen-3',
    creationDate: '2026-03-04',
    updatedDate: '2026-03-05',
    featuredStatus: false,
    accessLevel: 'PRO',
    customizableVariables: [
      { key: 'SUBJECT', label: 'Subject', defaultValue: 'a double smash wagyu beef patty crowned with melting sharp Wisconsin cheddar and crispy pancetta' },
      { key: 'LOCATION', label: 'Location', defaultValue: 'a glowing cast-iron skillet over roaring hickory hardwood charcoal embers' },
      { key: 'CAMERA MOVEMENT', label: 'Camera Movement', defaultValue: 'Subtle microscopic lateral glide tracking the downward drip of a molten cheese tear' },
      { key: 'LIGHTING', label: 'Lighting', defaultValue: 'Warm golden backlighting illuminating the translucent smoke plumes with rich appetizing specular pop' },
      { key: 'MOOD', label: 'Mood', defaultValue: 'mouthwatering, rustic, indulgent, and hypnotic' }
    ],
    copiesCount: 1240,
    savesCount: 680,
    isPublished: true,
    authorName: 'ChefCinematics'
  },
  {
    id: 'prompt-7',
    title: 'Ancient Sorceress Summoning Dragon Constellation',
    description: 'High-fantasy spellcasting choreography where glowing ethereal runes orbit the caster and form a living celestial wyrm.',
    category: 'Fantasy',
    tags: ['Fantasy', 'Magic', 'Dragon', 'VFX', 'Cinematic', 'Ethereal'],
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    fullPrompt: 'High fantasy cinematic masterpiece shot on Panavision 65mm. [SUBJECT] raises her hands atop [LOCATION]. Intricate golden arcane glyphs ignite in mid-air around her fingertips, swirling into a vortex that condenses into the translucent roaring head of an ethereal celestial dragon. [CAMERA MOVEMENT], wide theatrical framing. [LIGHTING], film grain, mystical particles, [MOOD].',
    exampleOutput: 'Delivers intricate spell particle physics, illuminating robes, billowing hair, and fluid dragon apparition.',
    recommendedUse: 'Runway Gen-3 Alpha, Sora, Kling 1.5 Pro',
    creationDate: '2026-03-02',
    updatedDate: '2026-03-05',
    featuredStatus: true,
    accessLevel: 'STUDIO',
    customizableVariables: [
      { key: 'SUBJECT', label: 'Subject', defaultValue: 'an ancient elven archmage in midnight-blue velvet robes threaded with constellations' },
      { key: 'LOCATION', label: 'Location', defaultValue: 'a shattered marble dais overlooking an endless abyss of floating shattered obelisks' },
      { key: 'CAMERA MOVEMENT', label: 'Camera Movement', defaultValue: '360-degree ascending spiral jib move accelerating as the magical rune circle expands' },
      { key: 'LIGHTING', label: 'Lighting', defaultValue: 'Dynamic bioluminescent cyan and gold volumetric lighting casting moving shadows on ancient ruins' },
      { key: 'MOOD', label: 'Mood', defaultValue: 'mythic, spellbinding, majestic, and electrifying' }
    ],
    copiesCount: 2450,
    savesCount: 1390,
    isPublished: true,
    authorName: 'MythosFX'
  },
  {
    id: 'prompt-8',
    title: 'Hyper-Realistic Snow Leopard Stalking In Blizzard',
    description: 'Documentary-grade National Geographic style wildlife sequence capturing a ghost leopard moving through Himalayan snow drifts.',
    category: 'Animals',
    tags: ['Wildlife', 'Animals', 'Documentary', 'Snow', '4K', 'National Geographic'],
    thumbnail: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800&auto=format&fit=crop&q=80',
    fullPrompt: 'Natural history documentary footage filmed on 800mm telephoto prime lens. [SUBJECT] stalks silently through [LOCATION]. Individual whiskers and frosted fur fibers tremble in the freezing gale. Swirling powdery snow drifts across the bottom frame. [CAMERA MOVEMENT], rack focus from crystalline snowflakes onto the amber dilated pupils. [LIGHTING], National Geographic documentary realism, [MOOD].',
    exampleOutput: 'Renders lifelike fur dynamics, wind turbulence, snow compaction under paws, and piercing predator eye focus.',
    recommendedUse: 'Hailuo Minimax, Runway Gen-3 Alpha, Kling 1.5',
    creationDate: '2026-03-03',
    updatedDate: '2026-03-06',
    featuredStatus: false,
    accessLevel: 'FREE',
    customizableVariables: [
      { key: 'SUBJECT', label: 'Subject', defaultValue: 'a magnificent snow leopard with muscular stealth posture and thick frosted tail' },
      { key: 'LOCATION', label: 'Location', defaultValue: 'a treacherous wind-scoured Tibetan mountain pass during a raging sub-zero blizzard' },
      { key: 'CAMERA MOVEMENT', label: 'Camera Movement', defaultValue: 'Super-telephoto slow horizontal track locked firmly on the piercing predator gaze' },
      { key: 'LIGHTING', label: 'Lighting', defaultValue: 'Diffused overcast polar daylight with cold blue ambient bounce and clean white snow bounce' },
      { key: 'MOOD', label: 'Mood', defaultValue: 'tense, silent, primal, wild, and breathtaking' }
    ],
    copiesCount: 1890,
    savesCount: 910,
    isPublished: true,
    authorName: 'WildPlanet'
  }
];

export const INITIAL_VIDEOS: CreatorVideo[] = [
  {
    id: 'vid-1',
    creatorId: 'usr-creator-1',
    creatorName: 'Elena Rostova',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    title: 'Cyberpunk Tokyo Drift 2088',
    description: 'Generated with Runway Gen-3 Alpha using the Cyberpunk Master Prompt from Prompt Vault. Color graded in DaVinci Resolve.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    category: 'Sci-Fi',
    tags: ['RunwayGen3', 'Cyberpunk', 'Cinematic', 'Neon'],
    promptUsed: 'Cinematic 35mm anamorphic footage of a cybernetic investigator in Neo-Shinjuku alley with rain reflections...',
    promptId: 'prompt-1',
    likesCount: 342,
    viewsCount: 1840,
    uploadDate: '2026-03-04',
    status: 'APPROVED'
  },
  {
    id: 'vid-2',
    creatorId: 'usr-creator-2',
    creatorName: 'Marcus Vance',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    title: 'Aura Noir — Fragrance Reveal',
    description: 'Commercial speculative spec ad for luxury cologne crafted using Kling 1.5 and Prompt Vault Product Master Prompt.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
    category: 'Product Videos',
    tags: ['Kling', 'Commercial', 'Luxury', 'Product'],
    promptUsed: 'Hyper-detailed 1000fps Phantom Flex commercial video of an obsidian cologne bottle with suspended gold flecks...',
    promptId: 'prompt-2',
    likesCount: 512,
    viewsCount: 3200,
    uploadDate: '2026-03-03',
    status: 'APPROVED'
  },
  {
    id: 'vid-3',
    creatorId: 'usr-creator-3',
    creatorName: 'SoraCraft Studios',
    creatorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    title: 'The Ridge Above Clouds',
    description: 'High altitude mountain flyover created with Luma Dream Machine. Prompt Vault nature master prompt customized for dolomite peaks.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
    category: 'Nature',
    tags: ['LumaDreamMachine', 'Drone', 'Dolomites'],
    promptUsed: 'Breathtaking IMAX 70mm aerial drone sequence sweeping at high velocity across dolomite ridge in golden hour...',
    promptId: 'prompt-3',
    likesCount: 428,
    viewsCount: 2650,
    uploadDate: '2026-03-02',
    status: 'APPROVED'
  }
];

export const DEMO_USERS: User[] = [
  {
    uid: 'usr-superadmin',
    name: 'Super Admin (Owner)',
    email: 'usagiptiktok@gmail.com',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    role: 'superadmin',
    isSuperAdmin: true,
    adminPermissions: {
      canManagePrompts: true,
      canManageCategories: true,
      canManageUsers: true,
      canManageSubscriptions: true,
      canManageVideos: true,
      canManageRequests: true,
      canManageReports: true,
      canManageAdmins: true
    },
    plan: 'STUDIO',
    subscriptionStatus: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01'
  },
  {
    uid: 'usr-admin',
    name: 'Vault Administrator',
    email: 'admin@promptvault.ai',
    photoURL: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    role: 'admin',
    isSuperAdmin: false,
    adminPermissions: {
      canManagePrompts: true,
      canManageCategories: true,
      canManageUsers: true,
      canManageSubscriptions: true,
      canManageVideos: true,
      canManageRequests: true,
      canManageReports: true,
      canManageAdmins: false
    },
    plan: 'STUDIO',
    subscriptionStatus: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01'
  },
  {
    uid: 'usr-studio',
    name: 'Maya Lin (Studio Creator)',
    email: 'creator@promptvault.ai',
    photoURL: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    role: 'user',
    plan: 'STUDIO',
    subscriptionStatus: 'active',
    createdAt: '2026-01-15',
    updatedAt: '2026-03-02'
  },
  {
    uid: 'usr-pro',
    name: 'Jordan Reed (Pro User)',
    email: 'pro@promptvault.ai',
    photoURL: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=120&auto=format&fit=crop&q=80',
    role: 'user',
    plan: 'PRO',
    subscriptionStatus: 'active',
    createdAt: '2026-02-01',
    updatedAt: '2026-03-03'
  },
  {
    uid: 'usr-free',
    name: 'Alex Rivera (Free Tier)',
    email: 'alex@example.com',
    photoURL: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=120&auto=format&fit=crop&q=80',
    role: 'user',
    plan: 'FREE',
    subscriptionStatus: 'active',
    createdAt: '2026-03-01',
    updatedAt: '2026-03-05'
  }
];
